package:
  name: osdag_latex_env
  version: "1.0.0"

source:
  path: ..

build:
  number: 0
  noarch: false
  script:

    - {{ PYTHON }} -m pip install . --no-deps -vv

    # Windows
    - mkdir %PREFIX%\\Library\\share\\osdag-latex-env    # [win]
    - robocopy assets\\windows\\bin %PREFIX%\\Library\\bin /E  || exit 0   # [win]
    - robocopy assets\\texmf %PREFIX%\\Library\\share\\osdag-latex-env /E  || exit 0  # [win]

    # Linux
    - mkdir -p $PREFIX/share/osdag-latex-env                # [linux]
    - cp -r assets/linux/bin/* $PREFIX/bin/             # [linux]
    - cp -r assets/texmf/* $PREFIX/share/osdag-latex-env  # [linux]

    # macOS
    - mkdir -p $PREFIX/share/osdag-latex-env                # [osx]
    - cp -r assets/macos/bin/* $PREFIX/bin/             # [osx]
    - cp -r assets/texmf/* $PREFIX/share/osdag-latex-env  # [osx]

requirements:
  build:
    - python
    - setuptools
    - pip
  host:
    - setuptools
    - pip
    - python
  run:
    - python

about:
  summary: Self-contained cross-platform LaTeX toolchain for Osdag
  license: LGPL-3.0-only
  license_family: LGPL
  home: https://osdag.fossee.in
  dev_url: https://github.com/osdag-admin/osdag-latex-env
  doc_url: https://github.com/osdag-admin/osdag-latex-env
